server:
    port: 10010
spring:
    application:
        name: sleuth-service
    zipkin:
        base-url: http://localhost:9411
    sleuth:
      sampler:
          # 采样率
          probability: 1
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka/

