server:
    port: 8092
spring:
    application:
        name: eureka-client
eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://peer1:8082/eureka/,http://peer2:8083/eureka/
        fetch-registry: true
        register-with-eureka: true
