server:
    port: 10120
spring:
    application:
        name: seata-account-service
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
                group: SEATA_GROUP
#        alibaba:
#            seata:
#                tx-service-group: my_test_tx_group
    datasource:
        password: lj#123
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.4.105:3306/seata-account
        username: oms
seata:
    tx-service-group: leowy_test_group
    registry:
        # 注册中心类型
        type: nacos
        nacos:
            application: seata-server
            server-addr: 127.0.0.1:8848
            namespace: public
    config:
        nacos:
            server-addr: 127.0.0.1:8848
            group: SEATA_GROUP
    service:
        vgroup-mapping:
            leowy_test_group: default
#        grouplist:
#            default: 192.168.4.105:8091
