server:
    port: 9010
spring:
    application:
        name: hystrix-service
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka/
management:
    endpoints:
      web:
        exposure:
            include: "*"
