server:
    port: 8082
spring:
    application:
        #指定服务名称
        name: eureka-server-1
eureka:
    instance:
        #指定主机地址
        hostname: peer1
    client:
        #指定是否要从注册中心获取服务（注册中心不需要开启）
        fetch-registry: false
        #指定是否要注册到注册中心（注册中心不需要开启）
        register-with-eureka: false
        service-url:
            defaultZone: http://peer2:8083/eureka/
