server:
    port: 8083
spring:
    application:
        #指定服务名称
        name: eureka-server-2
eureka:
    instance:
        #指定主机地址
        hostname: peer2
    client:
        #指定是否要从注册中心获取服务（注册中心不需要开启）
        fetch-registry: false
        #指定是否要注册到注册中心（注册中心不需要开启）
        register-with-eureka: false
        service-url:
            defaultZone: http://peer1:8082/eureka/
