server:
    port: 10110
spring:
    application:
        name: seata-storage-service
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
                group: SEATA_GROUP
#        alibaba:
#            seata:
#                tx-service-group: leowy_test_group
    datasource:
        password: lj#123
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.4.105:3306/seata-storage
        username: oms
seata:
    #    enabled: true
    tx-service-group: leowy_test_group
    registry:
        type: nacos
        nacos:
            application: seata-server
            group: SEATA_GROUP
            server-addr: 127.0.0.1:8848
    config:
      nacos:
          group: SEATA_GROUP
          server-addr: 127.0.0.1:8848
          namespace: "public"
    service:
        vgroup-mapping:
            leowy_test_group: default
        grouplist:
            default: 192.168.4.105:8091
