server:
    port: 10050
spring:
    application:
        name: sentinel-client
    cloud:
        sentinel:
            transport:
                # sentinel dashboard 地址
                dashboard: localhost:8080

            # 规则持久化
#            datasource:
#                flow:
#                    nacos:
#                        server-addr: localhost:8848
#                        group-id: DEFAULT_GROUP
#                        rule-type: flow
#                        dataId: ${spring.application.name}-flow-rules
##                        data-type: json
#                degrade:
#                    nacos:
#                        server-addr: localhost:8848
#                        group-id: DEFAULT_GROUP
#                        rule-type: degrade
#                        dataId: ${spring.application.name}-degrade-rules
#                        data-type: json
#                system:
#                    nacos:
#                        server-addr: localhost:8848
#                        group-id: DEFAULT_GROUP
#                        rule-type: system
##                        data-id: sentinel-rule
#                        dataId: ${spring.application.name}-system-rules
#                        ###  读取培训文件类型为json
#                        data-type: json
#                authority:
#                    nacos:
#                        server-addr: localhost:8848
#                        group-id: DEFAULT_GROUP
#                        rule-type: authority
##                        data-id: sentinel-rule
#                        dataId: ${spring.application.name}-authority-rules
#                        ###  读取培训文件类型为json
#                        data-type: json
#                param-flow:
#                    nacos:
#                        server-addr: localhost:8848
#                        group-id: DEFAULT_GROUP
#                        rule-type: param-flow
##                        data-id: sentinel-rule
#                        dataId: ${spring.application.name}-param-flow-rules
#                        ###  读取培训文件类型为json
#                        data-type: json
        nacos:
            discovery:
                # nacos注册中心地址
                server-addr: localhost:8848
